# Use kramdown as markdown parser engine.
markdown:     kramdown
markdown_ext: markdown,mkd,mkdn,md

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: true

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

gems:
  - jekyll-sitemap

timezone: Asia/Seoul

# Permalinks
permalink:     pretty

# Setup
title:         Kalkin7
tagline:       'blog'
description:   'Kalkin7's Blog'
url:           http://blogtest02.kalkinblog.tk/

author:
  name:        'kalkin7'
  url:         https://google.com/+Kkalkin7Hong

paginate:         7

# Custom vars
icon:          /assets/images/icon.png
cover:         /assets/images/cover.jpg

social:
  - icon:      twitter
    url:       https://twitter.com/kalkin_7
    desc:      Follow me on twitter

  - icon:      github
    url:       https://github.com/kalkin7
    desc:      Fork me on github

  - icon:      googleplus-alt
    url:       https://google.com/+Kkalkin7Hong
    desc:      Add me on google+

  - icon:      feed
    url:       http://blogtest02.kalkinblog.tk/atom.xml
    desc:      Subscribe to my feed
    
menu:
  - title:     Home
    url:       /
    
  - title:     About
    url:       /about
    
copyright:
  author:      kalkin7
  url:         http://blogtest02.kalkinblog.tk
  type_title:  Some rights reserved
  type_url:    http://creativecommons.org/licenses/by-nc/2.5